name: Optimize resource pack

on:
  push:
    tags:
      - "v*"

jobs:
  packsquash:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required

      - name: Make Optimized Pack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_optifine_mod: true
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename Optimized Pack
        run: |
          mv ./pack.zip "xali's Bushy Vanilla v3.2.0.zip"

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 557489
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: xali's Bushy Leaves v3.2.0.zip
          name: xali's Bushy Leaves v3.2.0
          version: v3.2.0
          version-type: release
          changelog-file: CHANGELOG.md
          game-versions: |
            1.19.2
            1.19.1
            1.19
            1.18
          loaders: |
            minecraft